spring:
  application:
    name: my-trading-app
  mvc:
    path-match:
      matching-strategy: ant-path-matcher
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  datasource:
    url: jdbc:h2:mem:myh2db
    driverClassName: org.h2.Driver
    username: test
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Server config
server:
  port: 9150

# Open API config
springdoc:
  packages-to-scan: com.example.tradingplatform
  paths-to-exclude: /swagger-resources/**
  writer-with-default-pretty-printer: true
  # URL to see Swagger: http://server:port/swagger-ui.html
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    docExpansion: none
    disable-swagger-default-url: true
  docs:
    title: Trading platform API
    description: Trading platform services from SIX Group
    version: 1.0.0
    terms: Product by Daniel Lobato